DIMO-Network/device-data-api

internal/rpc/user_device_data_api.go

PRO-1697 - GetSignals endpoint add filters for drilldowns

---

internal/models/signals_events.go
internal/rpc/user_device_data_api.go

PRO-1697 - Fix GetSignals

---

internal/rpc/user_device_data_api.go

fix requestCount and TotalCount

---

cmd/device-data-api/api.go
cmd/device-data-api/main.go
internal/rpc/user_device_data_api.go

PRO-1727 change where user grpc client is instantiated and passed in

---

internal/services/device_status_ingest_service.go

logging tweaks to help debug

---

internal/rpc/user_device_data_api.go

[PRO-1822] fix dates not coming in vdd summary

---

internal/controllers/device_data_controller.go

- remove 14 days gap on historical API

[SM-8] Change search to remove 14 days gap

---

internal/rpc/user_device_data_api.go

SM-249 - based count based on Powertrain

---

internal/rpc/user_device_data_api.go

SM-260 - Order results by highest count descending

---

cmd/device-data-api/api.go

`/v1/vehicle/:tokenID/history`
`/v1/vehicle/:tokenID/status`
`/user/device-data/:userDeviceID/status`

add cachehandler to more routes

---

cmd/device-data-api/api.go
cmd/device-data-api/main.go
internal/controllers/device_data_controller.go

handle not found from grpc error

---

cmd/device-data-api/api.go
internal/services/device_status_ingest_service.go
internal/services/device_status_ingest_service_test.go

SM-355 add source to snapshot below timestamp

---

internal/controllers/device_data_controller.go

Instead of returning the raw Elastic response for `/v2/vehicle/:tokenID/history`, return:
```
{
"statuses": [
{"id": "2ZBWLVbzpt6lAkqyi6TOZ2YFFIZ", …},
{"id": "2ZBWqf9OS5MYvawBC7PPoKyIX60", …},
…
]
}
```

Format v2 history

---

internal/controllers/download_data_controller.go

SM-503 set max retries, locallog improvement

---

internal/services/device_status_ingest_service.go

SM-360 - Write error to debug level

---

cmd/device-data-api/api.go

Added the authorization header value in the key func to determine whether a request is cached. 
The default key function uses `util.CopyString(c.Path())` The string copy should not be needed since the concatenation creates a new string for us to obtain the same behavior.
I also moved the refresh check to a skip handler, which I believe is the desired behavior based on this comment from the fiber docs.
> Next defines a function that is executed before creating the cache entry and can be used to execute the request without cache creation. If an entry already exists, it will be used. If you want to completely bypass the cache functionality in certain cases, you should use the [skip middleware](https://docs.gofiber.io/api/middleware/skip).

Cache updates SI-2432

---

internal/controllers/download_data_controller.go
internal/services/email_service.go

BUG-114 validate email before accepting job

---

cmd/device-data-api/api.go

update key func to use [OriginalURL()](https://docs.gofiber.io/api/ctx/#originalurl), which includes query parameters.

Updates cache key.

---

internal/controllers/device_data_controller.go

- Change ES query for odometer value

[SM-615] change query to get odometer values for distance driven

---

internal/controllers/device_data_controller.go

[SM-615] change odometer query for all distance
